### ISSUE TITLE
Google Analytics campaign tracking for footer links to www.mysociety.org

### ISSUE THREAD

**Issue by zarino** [mysociety/standard-footer#9]
Add UTM tracking parameters to the mysociety.org links in the footer template, so that we can see how many people are arriving at mysociety.org via footer links on our various sites.
# Link locations

![locations](https://cloud.githubusercontent.com/assets/739624/15117469/98e2a096-15ff-11e6-8ebe-fb143ea6bf0f.jpg)
# UTM parameters

| Link location | utm_source | utm_medium | utm_campaign | utm_content |
| :-: | --- | --- | --- | --- |
| **A** | `whytheyknowit.com` | link | mysoc_footer | footer donate now |
| **B** | `whytheyknowit.com` | link | mysoc_footer | footer logo |
| **C** | `whytheyknowit.com` | link | mysoc_footer | footer full legal details |

**Comment by wrightmartin** [comment]
- mysociety.org: https://github.com/mysociety/orgsites/pull/888 – deployed
- WriteToThem: https://github.com/mysociety/writetothem/pull/328 – deployed
- TWFY: https://github.com/mysociety/theyworkforyou/pull/1127 – deployed
- EveryPolitician: https://github.com/everypolitician/viewer-sinatra/pull/12568 – deployed
- WDTK: https://github.com/mysociety/whatdotheyknow-theme/pull/325 – deployed
- Gender Balance: https://github.com/everypolitician/gender-balance/pull/352 – deployed
- FMS: https://github.com/mysociety/fixmystreet/pull/1452 – deployed
- Mapumental: https://github.com/mysociety/mapumental/pull/534 – deployed
- MapIt + MapIt global: https://github.com/mysociety/mapit/pull/245 – deployed
- alaveteli.org: https://github.com/mysociety/alaveteli/pull/3367 – deployed
- Collideoscope: https://github.com/mysociety/fixmystreet/pull/1453 – deployed
- fixmystreet.org: https://github.com/mysociety/fixmystreet/pull/1454 – deployed
- mysociety.github.io: https://github.com/mysociety/mysociety.github.io/pull/27 – deployed
- Mapumental property: https://github.com/mysociety/mapumental/pull/533 – deployed
- sayit.mysociety.org: … https://github.com/mysociety/sayit.mysociety.org/issues/96 – deployed

**Comment by dracos** [comment]
All done.

**Comment by dracos** [comment]
Actually, sayit is missing the UTM stuff still

**Comment by dracos** [comment]
Added
